version: '3.8'

services:
  postgres:
    container_name: remindme-database
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: remindme
      POSTGRES_PASSWORD: password

volumes:
  postgres_data:
