name: CI

on: [push, pull_request]

env:
  DATABASE_URL: ${{secrets.DATABASE_URL}}
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}}
  CLERK_SECRET_KEY: ${{secrets.CLERK_SECRET_KEY}}
  NEXT_PUBLIC_CLERK_SIGN_UP_URL: /sign-up
  NEXT_PUBLIC_CLERK_SIGN_IN_URL: /sign-in
  NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL: /
  NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL: /
  NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL: /
  NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL: /

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: 'pnpm'

      - name: Setup Environment
        run: |
          echo "NODE_ENV=$NODE_ENV" >> GITHUB_ENV
          echo "DATABASE_URL=$DATABASE_URL" >> GITHUB_ENV
          echo "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY" >> GITHUB_ENV
          echo "CLERK_SECRET_KEY=$CLERK_SECRET_KEY" >> GITHUB_ENV
          echo "NEXT_PUBLIC_CLERK_SIGN_IN_URL=$NEXT_PUBLIC_CLERK_SIGN_IN_URL" >> GITHUB_ENV
          echo "NEXT_PUBLIC_CLERK_SIGN_UP_URL=$NEXT_PUBLIC_CLERK_SIGN_UP_URL" >> GITHUB_ENV
          echo "NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL=$NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL" >> GITHUB_ENV
          echo "NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL=$NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL" >> GITHUB_ENV

      - name: Install dependencies
        run: |
          pnpm install
          pnpm store prune

      - name: Database Migrations
        run: |
          pnpm db:push
          pnpm db:generate

      - name: Linting
        run: pnpm lint

      - name: Build
        run: pnpm build
